name: "Newline Linter"
description: "Lint files that don't end in a newline"

inputs:

  exclusion_pattern:
    description: Extended-grep-compatible pattern of file names to exclude
    required: false
    default: ""

runs:

  using: composite
  steps:

    - name: Lint newline
      run: ${{ github.action_path }}/git-no-newlines
      shell: bash
      env:
        EXCLUDE_PATTERN: ${{ inputs.exclusion_pattern }}

branding:
  color: green
  icon: slash
