on: push

jobs:

  lint_newlines:

    name: Lint newlines
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint newlines
        uses: fionn/newline-linter@master
